remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Cristian's homepage
description: My SNHU CAPSTONE will be published here!
header_pages:
  - index.md
  - artifacts.md
  - code-review.md
